version: '3.8'

services:
  ohif-viewer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_CONFIG=config/orthanc-config.js
        - PUBLIC_URL=/
    container_name: ohif-viewer
    ports:
      - '3000:80'
    environment:
      - PORT=80
      - PUBLIC_URL=/
    networks:
      - dicom-network
    depends_on:
      - orthanc
    restart: unless-stopped

  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc-server
    ports:
      - '4000:8042' # Orthanc web interface
      - '4242:4242' # DICOM port
    environment:
      - ORTHANC__NAME=OHIF-Orthanc
      - ORTHANC__DICOM_WEB__ENABLE=true
      - ORTHANC__DICOM_WEB__ROOT=/dicom-web/
      - ORTHANC__DICOM_WEB__ENABLE_METADATA_CACHE=true
      - ORTHANC__DICOM_WEB__ENABLE_WADO_RS=true
      - ORTHANC__DICOM_WEB__ENABLE_WADO_URI=true
      - ORTHANC__DICOM_WEB__ENABLE_QIDO_RS=true
      - ORTHANC__DICOM_WEB__ENABLE_STOW_RS=true
      - ORTHANC__AUTHENTICATION_ENABLED=false
      - ORTHANC__HTTP_CORS__ENABLED=true
      - ORTHANC__HTTP_CORS__ALLOWED_ORIGINS=*
      - ORTHANC__HTTP_CORS__ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ORTHANC__HTTP_CORS__ALLOWED_HEADERS=*
      - ORTHANC__DICOM_WEB__SERVE_JPEG=true
      - ORTHANC__DICOM_WEB__SERVE_PNG=true
    volumes:
      - orthanc-db:/var/lib/orthanc/db
      - orthanc-storage:/var/lib/orthanc/storage
      - ./orthanc-config:/etc/orthanc/:ro
    networks:
      - dicom-network
    restart: unless-stopped

networks:
  dicom-network:
    driver: bridge

volumes:
  orthanc-db:
    driver: local
  orthanc-storage:
    driver: local
