veservices:
  ohif-viewer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_CONFIG=config/orthanc-config.js
        - PUBLIC_URL=/
        - PORT=3000
      target: final
    container_name: ohif-viewer
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PUBLIC_URL=/
      - NODE_ENV=production
    networks:
      - dicom-network
services:
  ohif-viewer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_CONFIG=config/orthanc-config.js
        - PUBLIC_URL=/
        - PORT=3000
      target: final
    container_name: ohif-viewer
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PUBLIC_URL=/
      - NODE_ENV=production
    networks:
      - dicom-network
    depends_on:
      orthanc:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  orthanc:
    image: orthancteam/orthanc:24.8.1
    container_name: orthanc-server
    ports:
      - '4000:8042' # Orthanc web interface
      - '4242:4242' # DICOM port
    environment:
      - ORTHANC__NAME=OHIF-Orthanc
      - ORTHANC__DICOM_WEB__ENABLE=true
      - ORTHANC__DICOM_WEB__ROOT=/dicom-web/
      - ORTHANC__DICOM_WEB__ENABLE_METADATA_CACHE=true
      - ORTHANC__DICOM_WEB__ENABLE_WADO_RS=true
      - ORTHANC__DICOM_WEB__ENABLE_WADO_URI=true
      - ORTHANC__DICOM_WEB__ENABLE_QIDO_RS=true
      - ORTHANC__DICOM_WEB__ENABLE_STOW_RS=true
      - ORTHANC__AUTHENTICATION_ENABLED=false
      - ORTHANC__HTTP_CORS__ENABLED=true
      - ORTHANC__HTTP_CORS__ALLOWED_ORIGINS=*
      - ORTHANC__HTTP_CORS__ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ORTHANC__HTTP_CORS__ALLOWED_HEADERS=*
      - ORTHANC__DICOM_WEB__SERVE_JPEG=true
      - ORTHANC__DICOM_WEB__SERVE_PNG=true
      - ORTHANC__HTTP_COMPRESSION_ENABLED=true
      - ORTHANC__MAXIMUM_STORAGE_SIZE=0
      - ORTHANC__MAXIMUM_PATIENT_COUNT=0
    volumes:
      - orthanc-db:/var/lib/orthanc/db
      - orthanc-storage:/var/lib/orthanc/storage
      - ./orthanc-config:/etc/orthanc/:ro
    networks:
      - dicom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8042/system"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dicom-network:
    driver: bridge

volumes:
  orthanc-db:
    driver: local
  orthanc-storage:
    driver: local
